paths:
  /subscription:
    get:
      tags:
        - Subscription
      summary: Get user subscription details
      description: Returns the subscription details of the currently authenticated user.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
      responses:
        "200":
          description: Successfully fetched user subscription details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
  
  /subscription/transactions:
    get:
      tags:
        - Subscription
      summary: Get user transactions list
      description: Returns a list of transactions associated with the authenticated user.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
      responses:
        "200":
          description: Transactions fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transactions fetched successfully
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
  
  /subscription/purchase:
    post:
      tags:
        - Subscription
      summary: Purchase subscription
      description: Initiates a subscription purchase for the authenticated user.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: number
                  example: 1
                promo_code:
                  type: object
                  properties:
                    id:
                      type: string
                      example: PROMO123
                    amount_off:
                      type: number
                      allow: null
                      example: 10
                    percent_off:
                      type: number
                      allow: null
                      example: 10
      responses:
        "200":
          description: Successfully purchased subscription
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error

  /subscription/upgrade:
    put:
      tags:
        - Subscription
      summary: Upgrade subscription
      description: Upgrades the subscription for the authenticated user.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: number
                  example: 1
                promo_code:
                  type: object
                  properties:
                    id:
                      type: string
                      example: PROMO123
                    amount_off:
                      type: number
                      allow: null
                      example: 10
                    percent_off:
                      type: number
                      allow: null
                      example: 10
      responses:
        "200":
          description: Successfully upgraded subscription
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error

  /subscription/cancel:
    patch:
      tags:
        - Subscription
      summary: Cancel subscription
      description: Cancels the subscription for the authenticated user.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
      responses:
        "200":
          description: Successfully cancelled subscription
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error

  /subscription/payment-verification/webhook:
    post:
      tags:
        - Subscription
      summary: Payment verification webhook
      description: Handles payment verification webhook from Stripe.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                device_type:
                  type: number
                  enum: [1, 2, 3]
                  enumNames: [Mobile, Desktop, Tablet]
                  example: 2
      responses:
        "200":
          description: Payment verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Payment verification successful
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
