paths:
  /plan/{plan_id}:
    get:
      tags:
        - Plan
      summary: Get a single plan by ID
      description: Returns details of a specific plan by its ID.
      security: []
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
        - name: plan_id
          in: path
          required: true
          schema:
            type: number
          description: ID of the plan to retrieve
          example: 1
      responses:
        '200':
          description: A single plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: Plan ID
                    example: 1
                  name:
                    type: string
                    description: Plan name
                    example: Basic
                  price_id:
                    type: string
                    description: Price ID
                    example: price_1RSz7WSD0McdkBvaLyknqCsJ
                  price:
                    type: number
                    description: Price of the plan
                    example: 50
                  tax_percentage:
                    type: number
                    description: Tax percentage
                    example: 0
                  features:
                    type: string
                    description: Plan features
                    nullable: true
                    example: null
                  type:
                    type: string
                    description: Plan type
                    enum: [1, 2]
                    enumNames: [Basic, Pro]
                    example: 1
                  provider:
                    type: string
                    description: Provider ID
                    enum: [1, 2]
                    enumNames: [Stripe, Razorpay]
                    example: 1
                  currency:
                    type: string
                    description: Currency ID
                    enum: [1, 2]
                    enumNames: [INR, USD]
                    example: "2"
                  interval:
                    type: string
                    description: Billing interval
                    enum: [1, 2, 3, 4]
                    enumNames: [Daily, Weekly, Monthly, Yearly]
                    example: "3"
                  interval_count:
                    type: number
                    description: Interval count
                    example: 1
                  status:
                    type: string
                    description: Plan status
                    enum: [1, 2]
                    enumNames: [Active, Inactive]
                    example: "1"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to fetch plan

  /plan:
    get:
      tags:
        - Plan
      summary: Get a list of available plans
      description: Returns a list of available plans.
      security: []
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
        - name: plan_id
          in: query
          required: false
          schema:
            type: number
          description: ID of the plan to retrieve
          example: 1
        - name: interval
          in: query
          required: false
          schema:
            type: number
            enum: [1, 2, 3, 4]
            enumNames: [Daily, Weekly, Monthly, Yearly]
          description: Filter by interval
          example: 3
      responses:
        '200':
          description: A list of plans
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: Plan ID
                      example: 1
                    name:
                      type: string
                      description: Plan name
                      example: Basic
                    price_id:
                      type: string
                      description: Price ID
                      example: price_1RSz7WSD0McdkBvaLyknqCsJ
                    price:
                      type: number
                      description: Price of the plan
                      example: 50
                    tax_percentage:
                      type: number
                      description: Tax percentage
                      example: 0
                    features:
                      type: string
                      description: Plan features
                      nullable: true
                      example: null
                    type:
                      type: string
                      description: Plan type
                      enum: [1, 2]
                      enumNames: [Basic, Pro]
                      example: 1
                    provider:
                      type: string
                      description: Provider ID
                      enum: [1, 2]
                      enumNames: [Stripe, Razorpay]
                      example: 1
                    currency:
                      type: string
                      description: Currency ID
                      enum: [1, 2]
                      enumNames: [INR, USD]
                      example: "2"
                    interval:
                      type: string
                      description: Billing interval
                      enum: [1, 2, 3, 4]
                      enumNames: [Daily, Weekly, Monthly, Yearly]
                      example: "3"
                    interval_count:
                      type: number
                      description: Interval count
                      example: 1
                    status:
                      type: string
                      description: Plan status
                      enum: [1, 2]
                      enumNames: [Active, Inactive]
                      example: "1"
        '500':
          description: Internal server error fetching plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to fetch plans
