paths:
  /subscription/transactions:
    get:
      tags:
        - Subscription
      summary: Get transactions list
      description: Returns a list of transactions.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is en)
        - name: user_id
          in: query
          required: false
          schema:
            type: number
        - name: status
          in: query
          required: false
          schema:
            type: number
            enum: [1, 2]
            enumNames: [Active, Inactive]
          example: 1
        - name: payment_status
          in: query
          required: false
          schema:
            type: number
            enum: [1, 2, 3]
            enumNames: [Paid, Failed, Pending ]
          example: 1
        - name: perPage
          in: query
          required: false
          schema:
            type: number
          description: Number of records per page
          example: 10
        - name: page
          in: query
          required: false
          schema:
            type: number
          description: Page number
          example: 1
        - name: orderBy
          in: query
          required: false
          schema:
            type: string
          description: Order by field
          example: "created_at"
        - name: orderDir
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
          description: Order direction (asc or desc)
          example: "asc"
      responses:
        "200":
          description: Transactions fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transactions fetched successfully
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
